// Centralized feature categorization for 5e rules - features are categorized here regardless of source (class, race, background, etc.)

export const featuresToIgnore = [
    "Ability Score Improvement",
    "Bardic Inspiration",
    "Brutal Critical",
    "Channel Divinity",
    "Divine Domain",
    "Domain Spells",
    "Druid Circle",
    "Druidic",
    "Extra Attack",
    "Ki",
    "Martial Archetype",
    "Monastic Tradition",
    "Primal Path",
    "Rage",
    "Ranger Archetype",
    "Roguish Archetype",
    "Sacred Oath",
    "Sorcerous Origin",
    "Spellcasting",

];

export const actions = [
    "Arcane Charge",
    "Avenging Angel",
    "Bestial Fury",
    "Channel Divinity: Abjure Enemy",
    "Channel Divinity: Charm Animals and Plants",
    "Channel Divinity: Invoke Duplicity",
    "Channel Divinity: Knowledge of the Ages",
    "Channel Divinity: Nature's Wrath",
    "Channel Divinity: Preserve Life",
    "Channel Divinity: Radiance of the Dawn",
    "Channel Divinity: Read Thoughts",
    "Channel Divinity: Turn the Faithless",
    "Channel Divinity: Turn Undead",
    "Cleansing Touch",
    "Cloak of Shadows",
    "Countercharm",
    "Dark Delirium",
    "Destroy Undead",
    "Divine Sense",
    "Divine Strike",
    "Draconic Presence",
    "Eldritch Strike",
    "Empty Body",
    "Fey Presence",
    "Holy Nimbus",
    "Improved Divine Smite",
    "Improved War Magic",
    "Master Transmuter",
    "Primeval Awareness",
    "Quivering Palm",
    "Sneak Attack",
    "Stillness of Mind",
    "The Third Eye",
    "Vanish"
];

export const bonusActions = [
    "Channel Divinity: Vow of Enmity",
    "Combat Wild Shape (Wild Companion)",
    "Combat Wild Shape",
    "Cunning Action",
    "Exceptional Training",
    "Fast Hands",
    "Flexible Casting: Converting Spell Slot",
    "Flexible Casting: Creating Spell Slots",
    "Font of Magic",
    "Patient Defense",
    "Step of the Wind",
    "Versatile Trickster",
    "War Magic"
];

export const reactions = [
    "Beguiling Defenses",
    "Channel Divinity: War God's Blessing",
    "Entropic Ward",
    "Instinctive Charm",
    "Projected Ward",
    "Soul of Vengeance",
    "Wrath of the Storm"
];

export const characterAdvancement = [
    "Acolyte of Nature",
    "Additional Magical Secrets",
    "Arcane Tradition",
    "Aura improvements",
    "Bard College",
    "Blessings of Knowledge",
    "Bonus Cantrip",
    "Bonus Proficiencies",
    "Bonus Proficiency",
    "Darkvision",
    "Divine Health",
    "Draconic Ancestry",
    "Draconic Resilience",
    "Dragon Ancestor",
    "Dwarven Toughness",
    "Eldritch Invocations",
    "Evocation Savant",
    "Fast Movement",
    "Favored Enemy",
    "Fighting Style",
    "Fleet of Foot",
    "Hellish Resistance",
    "High Elf Cantrip",
    "Mage Hand Legerdemain",
    "Magical Secrets",
    "Martial Arts",
    "Natural Explorer",
    "Natural Illusionist",
    "Oath Spells",
    "Otherworldly Patron",
    "Pact Boon",
    "Pact Magic",
    "Primal Champion",
    "Primal Knowledge",
    "Purity of Body",
    "Ranger's Companion",
    "Skillful",
    "Versatile",
    "Thieves' Cant",
    "Timeless Body",
    "Unarmored Defense",
    "Unarmored Movement",
    "Weapon Bond"
];