// Centralized feature categorization for 2024 rules - features are categorized here regardless of source (class, race, background, etc.)

export const featuresToIgnore = [
    "Ability Score Improvement",
    "Barbarian Subclass",
    "Bard Bard Subclass",
    "Bardic Inspiration",
    "Channel Divinity",
    "Cleric Subclass",
    "Darkvision",
    "Druid Subclass",
    "Eldritch Invocations",
    "Epic Boon",
    "Extra Attack",
    "Two Extra Attacks",
    "Three Extra Attacks",
    "Feat",
    "Fighter Subclass",
    "Fighting Style",
    "Monk Subclass",

    "Paladin Subclass",
    "Rage",
    "Ranger Subclass",
    "Assassin's Tools",
    "Rogue Subclass",
    "Sorcerer Subclass",
    "Spellcasting",
    "Subclass feature",
    "Warlock Subclass",
    "Wizard Subclass"
];

export const actions = [
    "Arcane Charge",
    "Bestial Fury",
    "Cunning Strike",
    "Eldritch Strike",
    "Eldritch Blast",
    "Empowered Strikes",
    "Favored Enemy",
    "Hex",
    "Improved War Magic",
    "Precise Hunter",
    "Sacred Weapon",
    "Signature Spells",
    "Sneak Attack",
    "Spell Mastery",
    "Studied Attacks",
    "Supreme Sneak",
    "Tactical Master",
    "Tireless",
    "War Magic",
    "Witch Bolt",
    "Words of Creation"
];

export const bonusActions = [
    "Berserker Charge",
    "Cunning Action",
    "Devious Strikes",
    "Exceptional Training",
    "Fast Hands",
    "Fighting Style Bonus",
    "Instinctive Pounce",
    "Large Form",
    "Nature's Veil",
    "Steady Aim",
    "Tactical Shift"
];

export const reactions = [
    "Beguiling Defenses",
    "Bend Fate",
    "Countercharm",
    "Deflect Energy",
    "Feather Fall",
    "Opportunity Attack",
    "Riposte",
    "Shield Block",
    "Soul of Vengeance",
    "Uncanny Dodge"
];

export const characterAdvancement = [
    "(capstone - depends on subclass)",
    "Body and Mind",
    "Damage Resistance",
    "Deft Explorer",
    "Divine Order",
    "Draconic Ancestry",
    "Draconic Resilience",
    "Draconic Spells",
    "Druidic",
    "Dwarven Toughness",
    "Elfish Lineage",
    "Feral Senses",
    "Fiendish Legacy",
    "Fiendish Legacies",
    "Keen Senses",
    "Thieves' Cant",
    "Martial Arts",
    "Monastic Traditions",
    "Oath Spells",
    "Magical Secrets",
    "Pact Boon",
    "Pact Magic",
    "Primal Champion",
    "Primal Knowledge",
    "Primal Order",
    "Scholar",
    "Slippery Mind",
    "Skillful",
    "Student of War",
    "Versatile",
    "Abjuration Savant",
    "Divination Savant",
    "Evocation Savant",
    "Spell Breaker"
];