// Centralized feature categorization for both 5e and 2024 rulesets.
// Features are categorized here regardless of source (class, race, background, etc.)

const categories5e = {
    featuresToIgnore: [
        "Ability Score Improvement",
        "Bardic Inspiration",
        "Brutal Critical",
        "Channel Divinity",
        "Divine Domain",
        "Domain Spells",
        "Druid Circle",
        "Druidic",
        "Extra Attack",
        "Ki",
        "Martial Archetype",
        "Monastic Tradition",
        "Primal Path",
        "Rage",
        "Ranger Archetype",
        "Roguish Archetype",
        "Sacred Oath",
        "Sorcerous Origin",
        "Spellcasting",
    ],

    actions: [
        "Arcane Charge",
        "Avenging Angel",
        "Bestial Fury",
        "Channel Divinity: Abjure Enemy",
        "Channel Divinity: Charm Animals and Plants",
        "Channel Divinity: Invoke Duplicity",
        "Channel Divinity: Knowledge of the Ages",
        "Channel Divinity: Preserve Life",
        "Channel Divinity: Radiance of the Dawn",
        "Channel Divinity: Read Thoughts",
        "Channel Divinity: Turn the Faithless",
        "Channel Divinity: Turn Undead",
        "Cleansing Touch",
        "Cloak of Shadows",
        "Countercharm",
        "Dark Delirium",
        "Destroy Undead",
        "Divine Sense",
        "Divine Strike",
        "Draconic Presence",
        "Eldritch Strike",
        "Empty Body",
        "Fey Presence",
        "Holy Nimbus",
        "Improved Divine Smite",
        "Improved War Magic",
        "Master Transmuter",
        "Primeval Awareness",
        "Quivering Palm",
        "Sneak Attack",
        "Stillness of Mind",
        "The Third Eye",
        "Vanish"
    ],

    bonusActions: [
        "Channel Divinity: Vow of Enmity",
        "Vow of Enmity",
        "Combat Wild Shape (Wild Companion)",
        "Combat Wild Shape",
        "Cunning Action",
        "Exceptional Training",
        "Fast Hands",
        "Flexible Casting: Converting Spell Slot",
        "Flexible Casting: Creating Spell Slots",
        "Font of Magic",
        "Patient Defense",
        "Step of the Wind",
        "Versatile Trickster",
        "War Magic"
    ],

    reactions: [
        "Beguiling Defenses",
        "Bend Fate",
        "Channel Divinity: War God's Blessing",
        "Entropic Ward",
        "Instinctive Charm",
        "Projected Ward",
        "Wrath of the Storm"
    ],

    characterAdvancement: [
        "Acolyte of Nature",
        "Additional Magical Secrets",
        "Arcane Tradition",
        "Aura improvements",
        "Bard College",
        "Blessings of Knowledge",
        "Bonus Cantrip",
        "Bonus Proficiencies",
        "Bonus Proficiency",
        "Darkvision",
        "Divine Health",
        "Draconic Ancestry",
        "Draconic Resilience",
        "Dragon Ancestor",
        "Dwarven Toughness",
        "Eldritch Invocations",
        "Evocation Savant",
        "Fast Movement",
        "Favored Enemy",
        "Fighting Style",
        "Fleet of Foot",
        "Hellish Resistance",
        "High Elf Cantrip",
        "Mage Hand Legerdemain",
        "Magical Secrets",
        "Martial Arts",
        "Natural Explorer",
        "Natural Illusionist",
        "Oath Spells",
        "Otherworldly Patron",
        "Pact Boon",
        "Pact Magic",
        "Primal Champion",
        "Primal Knowledge",
        "Purity of Body",
        "Ranger's Companion",
        "Skillful",
        "Versatile",
        "Thieves' Cant",
        "Timeless Body",
        "Unarmored Defense",
        "Unarmored Movement",
        "Weapon Bond"
    ]
};

const categories2024 = {
    featuresToIgnore: [
        "Ability Score Improvement",
        "Barbarian Subclass",
        "Bard Bard Subclass",
        "Bardic Inspiration",
        "Channel Divinity",
        "Cleric Subclass",
        "Celestial Resistance",
        "Darkvision",
        "Druid Subclass",
        "Eldritch Invocations",
        "Epic Boon",
        "Extra Attack",
        "Two Extra Attacks",
        "Three Extra Attacks",
        "Feat",
        "Fighter Subclass",
        "Fighting Style",
        "Monk Subclass",
        "Paladin Subclass",
        "Rage",
        "Ranger Subclass",
        "Assassin's Tools",
        "Rogue Subclass",
        "Sorcerer Subclass",
        "Spellcasting",
        "Subclass feature",
        "Warlock Subclass",
        "Wizard Subclass"
    ],

    actions: [
        "Arcane Charge",
        "Bestial Fury",
        "Cunning Strike",
        "Eldritch Strike",
        "Eldritch Blast",
        "Empowered Strikes",
        "Favored Enemy",
        "Hex",
        "Improved War Magic",
        "Precise Hunter",
        "Sacred Weapon",
        "Signature Spells",
        "Sneak Attack",
        "Spell Mastery",
        "Studied Attacks",
        "Supreme Sneak",
        "Tactical Master",
        "Tireless",
        "War Magic",
        "Witch Bolt",
        "Words of Creation"
    ],

    bonusActions: [
        "Berserker Charge",
        "Cunning Action",
        "Devious Strikes",
        "Exceptional Training",
        "Fast Hands",
        "Fighting Style Bonus",
        "Instinctive Pounce",
        "Large Form",
        "Nature's Veil",
        "Steady Aim",
        "Tactical Shift"
    ],

    reactions: [
        "Beguiling Defenses",
        "Bend Fate",
        "Countercharm",
        "Deflect Energy",
        "Feather Fall",
        "Interception",
        "Opportunity Attack",
        "Riposte",
        "Shield Block",
        "Soul of Vengeance",
        "Uncanny Dodge"
    ],

    characterAdvancement: [
        "(capstone - depends on subclass)",
        "Body and Mind",
        "Damage Resistance",
        "Deft Explorer",
        "Divine Order",
        "Draconic Ancestry",
        "Draconic Resilience",
        "Draconic Spells",
        "Druidic",
        "Dwarven Toughness",
        "Elfish Lineage",
        "Feral Senses",
        "Fiendish Legacy",
        "Fiendish Legacies",
        "Keen Senses",
        "Thieves' Cant",
        "Martial Arts",
        "Monastic Traditions",
        "Oath Spells",
        "Magical Secrets",
        "Pact Boon",
        "Pact Magic",
        "Primal Champion",
        "Primal Knowledge",
        "Primal Order",
        "Scholar",
        "Slippery Mind",
        "Skillful",
        "Student of War",
        "Versatile",
        "Abjuration Savant",
        "Divination Savant",
        "Evocation Savant",
        "Spell Breaker"
    ]
};

export function getCategories(ruleset) {
    return ruleset === '2024' ? categories2024 : categories5e;
}

export { categories5e, categories2024 };
